### PR TITLE
refactor: starts checking for custom error reverts

### PR DESCRIPTION
**Pull request by wei3erHase**
Guys, i've discovered thanks to our good @0xng that the `revertedWith()` expectation was not working with our current resolutions. I've updated the package json and added a test using that expectation.

### CODE REVIEW

**Comment by wei3erHase** [comment]
Just realized, we're not testing e2e/unit on pull requests!

**Comment by 404skillz** [comment]
Nice catch ! Do we still need resolutions ? (Maybe we do, since we can't update hardhat to latest version on this repo cause it breaks everything)

**Review by wei3erHase — COMMENTED** [review]
> BTW: Please fix conflict 😊

i do not have a conflict. YOU have a conflict!

thkx tho, i cannot approve my own PR

**Review by 0xGorilla — APPROVED** [review]
Watch out with the dependency changes in the other PR!

**Comment by wei3erHase** [comment]
@0xGorilla I see now! will handle and get back soon

**Pull request merged**
