### PR TITLE
Downgrade colors.js to 1.4.0

### PR DESCRIPTION
**Pull request by gas1cent**
See this for context https://github.com/Marak/colors.js/issues/285

### CODE REVIEW

**Comment by 404skillz** [comment]
Is there a way we can set this in `resolutions` within the `package.json` ? I fear someone might delete the `yarn.lock` and this change is missed :)

**Comment by drgorillamd** [comment]
> Is there a way we can set this in `resolutions` within the `package.json` ? I fear someone might delete the `yarn.lock` and this change is missed :)

yep, just pushed it (here)

**Comment by drgorillamd** [comment]
> Is there a way we can set this in `resolutions` within the `package.json` ? I fear someone might delete the `yarn.lock` and this change is missed :)

Just added it, `npm list colors` :
image

**Review by 404skillz — APPROVED** [review]
Great work guys ! Thank you !

**Pull request merged**
