### PR TITLE
chore: add README instructions for adding secrets for GitHub workflows

### PR DESCRIPTION
**Pull request by zetshiro**
See title.

### CODE REVIEW

**Comment by 0xged** [comment]
@zetshiro I had thought about making the "gas report" CI condition to the detection of `CC` environment variable. 

What do you think? Additionally it would be cool to clarify that coinmarketcap key and cc are pretty much optional 😬

**Comment by zetshiro** [comment]
> @zetshiro I had thought about making the "gas report" CI condition to the detection of `CC` environment variable.
> 
> What do you think? Additionally it would be cool to clarify that coinmarketcap key and cc are pretty much optional 😬

something like this? (pseudo-code)

```
if (env.CC) {
  npx codechecks
}
```

i think this is good and making the coinmarketcap and cc optional makes sense.

**Comment by zetshiro** [comment]
i will update the pr soon with the suggested change above 👍

**Comment by wei3erHase** [comment]
@zetshiro i'm closing the PR because of inactivity, please feel free to reopen it any time
thanks for contributing and choosing our boilerplate!

**Pull request closed without merging**
